/* This file is generated by scripts automatively.
 * do not change it by hand.
 */

#include "../utils/template.h"
#include "../base/TypeFunc.h"

#include "../neuron/lif/LIFData.h"
#include "../synapse/static/StaticData.h"

size_t (*getTypeSize[])() = {
	getLIFSize,
	getStaticSize
};

void* (*mallocType[])() = {
	mallocLIF,
	mallocStatic
};

void* (*allocType[])(size_t num) = {
	allocLIF,
	allocStatic
};

int (*freeType[])(void *pCPU) = {
	freeLIF,
	freeStatic
};

int (*allocTypePara[])(void *pCPU, size_t num) = {
	allocLIFPara,
	allocStaticPara
};

int (*freeTypePara[])(void *pCPU) = {
	freeLIFPara,
	freeStaticPara
};

int (*saveType[])(void *pCPU, size_t num, FILE *f) = {
	saveLIF,
	saveStatic
};

void* (*loadType[])(size_t num, FILE *f) = {
	loadLIF,
	loadStatic
};

void (*updateType[])(Connection *, void *, real *, uinteger_t *, uinteger_t*,  size_t, size_t, size_t, int) = {
	updateLIF,
	updateStatic
};

bool (*isEqualType[])(void *p1, void *p2, size_t num, size_t *shuffle1, size_t *shuffle2) = {
	isEqualLIF,
	isEqualStatic
};

int (*sendType[])(void *data, int dest, int tag, MPI_Comm comm) = {
	sendLIF,
	sendStatic
};

void * (*recvType[])(int src, int tag, MPI_Comm comm) = {
	recvLIF,
	recvStatic
};

