/* This file is generated by scripts automatively.
 * do not change it by hand.
 */

#include "../utils/template.h"
#include "../base/TypeFunc.h"

#include "../neuron/lif/LIFData.h"
#include "../synapse/static/StaticData.h"
#include "../synapse/poisson/PoissonData.h"

size_t (*getTypeSize[])() = {
	getLIFSize,
	getStaticSize,
	getPoissonSize
};

void* (*mallocType[])() = {
	mallocLIF,
	mallocStatic,
	mallocPoisson
};

void* (*allocType[])(size_t num) = {
	allocLIF,
	allocStatic,
	allocPoisson
};

int (*freeType[])(void *pCPU) = {
	freeLIF,
	freeStatic,
	freePoisson
};

int (*allocTypePara[])(void *pCPU, size_t num) = {
	allocLIFPara,
	allocStaticPara,
	allocPoissonPara
};

int (*freeTypePara[])(void *pCPU) = {
	freeLIFPara,
	freeStaticPara,
	freePoissonPara
};

int (*saveType[])(void *pCPU, size_t num, const string &path) = {
	saveLIF,
	saveStatic,
	savePoisson
};

void* (*loadType[])(size_t num, const string &path) = {
	loadLIF,
	loadStatic,
	loadPoisson
};

void (*updateType[])(Connection *, void *, real *, uinteger_t *, uinteger_t*,  size_t, size_t, size_t, int) = {
	updateLIF,
	updateStatic,
	updatePoisson
};

bool (*isEqualType[])(void *p1, void *p2, size_t num, uinteger_t *shuffle1, uinteger_t *shuffle2) = {
	isEqualLIF,
	isEqualStatic,
	isEqualPoisson
};

int (*logRateNeuron[])(void *p1, const char *name) = {
	logRateLIF,
	NULL,
	NULL
};

int (*shuffleSynapse[])(void *p1, uinteger_t *shuffle1, size_t num) = {
	NULL,
	shuffleStatic,
	shufflePoisson
};

int (*sendType[])(void *data, int dest, int tag, MPI_Comm comm) = {
	sendLIF,
	sendStatic,
	sendPoisson
};

void * (*recvType[])(int src, int tag, MPI_Comm comm) = {
	recvLIF,
	recvStatic,
	recvPoisson
};

